# Generated by Django 4.2.7 on 2023-11-16 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_remove_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
