# Generated by Django 4.2.7 on 2023-11-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
