# Generated by Django 4.2.7 on 2023-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
