# Generated by Django 4.2.7 on 2023-11-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0009_booking_selected_time_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(default=1, max_length=880),
            preserve_default=False,
        ),
    ]
