# Generated by Django 4.2.7 on 2023-11-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0010_remove_booking_selected_time_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[(1, '9:00 am-10:00 am'), (2, '10:00 am-11:00 am'), (3, '11:00 am-12:00 pm'), (4, '12:00 pm-1:00 pm')], default='1', max_length=100),
        ),
    ]
