# Generated by Django 4.2.7 on 2023-11-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0011_alter_booking_date_alter_booking_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('9:00 am-10:00 am', '9:00 am-10:00 am'), (2, '10:00 am-11:00 am'), (3, '11:00 am-12:00 pm'), (4, '12:00 pm-1:00 pm')], default='1', max_length=100),
        ),
    ]
