# Generated by Django 4.2.7 on 2023-11-18 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resto', '0012_alter_booking_date_alter_booking_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('9:00 am-10:00 am', '9:00 am-10:00 am'), ('10:00 am-11:00 am', '10:00 am-11:00 am'), ('11:00 am-12:00 pm', '11:00 am-12:00 pm'), ('12:00 pm-1:00 pm', '12:00 pm-1:00 pm')], default='1', max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
