# Generated by Django 4.2.7 on 2023-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
