# Generated by Django 4.2.7 on 2023-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0015_contact_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='your_field',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=5, max_length=254),
            preserve_default=False,
        ),
    ]
