# Generated by Django 4.2.7 on 2023-11-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0016_rename_content_contact_message_remove_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='your_field',
            new_name='name',
        ),
    ]
