# Generated by Django 4.2.7 on 2023-11-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0019_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
