# Generated by Django 4.2.7 on 2023-11-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0021_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
