# Generated by Django 4.2.7 on 2023-11-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0023_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
