# Generated by Django 4.2.7 on 2023-12-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0028_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
