# Generated by Django 4.2.7 on 2023-12-03 06:04

from django.db import migrations, models
import resto.models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
