# Generated by Django 4.2.7 on 2023-12-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0031_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
