# Generated by Django 4.2.7 on 2023-12-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0033_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.svg', upload_to='pics'),
        ),
    ]
