# Generated by Django 4.2.7 on 2023-12-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0036_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
